# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rtsne_cpp <- function(X, no_dims_in, perplexity_in, theta_in, num_threads, max_iter, distance_precomputed) {
    .Call('_Rtsne_multicore_Rtsne_cpp', PACKAGE = 'Rtsne.multicore', X, no_dims_in, perplexity_in, theta_in, num_threads, max_iter, distance_precomputed)
}

